name: Infrastructures Deployment

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Install TF
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
          terraform -v

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id "${{secrets.AWS_ACCESS_KEY_ID}}"
          aws configure set aws_secret_access_key "${{secrets.AWS_SECRET_ACCESS_KEY}}"
          aws configure set region "${{secrets.AWS_SECRET_REGION}}"


      - name: Create Infrastructures
        run: |
          cd tf
          terraform init
          terraform apply -var-file region.eu-north-1.tfvars -auto-approve
          polybot1_ip=$(terraform output -raw polybot1_public_ip)
          polybot2_ip=$(terraform output -raw polybot2_public_ip)
          echo "polybot1_ip=$polybot1_ip" >> $GITHUB_ENV
          echo "polybot2_ip=$polybot2_ip" >> $GITHUB_ENV
          
      - name: Create inventory file from output
        run: |
          touch inventory.txt
          echo "[polybot]" > inventory.txt
          echo "polybot1 ansible_host=$polybot1_ip ansible_user=ubuntu" >> inventory.txt
          echo "polybot2 ansible_host=$polybot2_ip ansible_user=ubuntu" >> inventory.txt
          cat inventory.txt
          mv inventory.txt ../ansible

      - name: Install Ansible
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible -y
          ansible --version

      - name: Run Ansible Playbook
        run: |
          cd ansible
          echo "${{secrets.KEY_PEM}}" > 10-9-2024-ec2.pem
          sudo chmod 400 10-9-2024-ec2.pem
          ssh -o StrictHostKeyChecking=no -i 10-9-2024-ec2.pem ubuntu@$polybot1_ip "whoami"
          ssh -o StrictHostKeyChecking=no -i 10-9-2024-ec2.pem ubuntu@$polybot2_ip "whoami"
          ansible-inventory -i inventory.txt --list
          ls
          ansible-playbook -i inventory.txt --private-key key.pem playbook.yml
