name: Polybot Microservice Deployment

on:
  push:
    paths:
      - 'polybot/**'
    branches:
      - shachar

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          # TODO your implementation here.... 
          cd polybot
          docker build -t . polybot
          docker tag polybot shacharavraham/polybot
          docker push shacharavraham/polybot

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2
      - name: Deploy new version
        run: |         
          # TODO your implementation here....
          cd tf
          terraform init
          terraform apply -var-file region.eu-north-1.tfvars
          polybot1_ip=$(terraform output -raw polybot1_public_ip)
          polybot2_ip=$(terraform output -raw polybot2_public_ip)
          cd ../ansible
          sed -i "s/\(polybot1 ansible_host=\)[^ ]*/\1$polybot1_ip/" inventory.txt
          sed -i "s/\(polybot2 ansible_host=\)[^ ]*/\1$polybot2_ip/" inventory.txt
          ansible-playbook -i inventory.txt playbook.yml