name: Yolo5 Microservice Deployment

on:
  push:
    paths:
      - 'yolo5/**'
    branches:
      - shachar

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          # TODO your implementation here....          
          cd yolo5
          docker build -t . yolo5
          dcoker tag polybot shacharavraham/yolo5
          docker push shacharavraham/yolo5

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2
      - name: Deploy new version
        run: |         
          # TODO your implementation here....
          cd tf
          terraform init
          terraform apply -var-file region.eu-north-1.tfvars
     
